enable: true
thirst:
  max-value: 100 # 最大值
  natural-depletion: 1 # 自然流失1属性值每秒
  death-punishment: # 死亡惩罚
    enable: true    # 开关
    value: 60       # 复活时口渴值为上限的百分之几。取之范围为0～100
    effect:         # 复活时赋予的效果
      first:        # 可列多个
        bundle: "abc" # 效果包的ID
        duration: 60  # 持续时间 秒
  effect-bundles:
    "缺水":
      type: "元素负面效果"
      PotionEffect:
        effect-1:
          potion-type: "SLOW"
          amplifier: 0
      ChatMessage:
        effect-1:
          message: "你现在有一点缺水了"
  effects:
    "level-1":
      range: [0, 10]
      percentage: true
      bundle: "缺水"
      duration: 20
      message-sender: "ChatMessage"
      message: "河水河水河水河水"
    "level-2":
      range: [90, 100]
      percentage: true
      bundle: "速度升级"
      duration: 20
      message-sender: "ChatMessage"
      message: "你好滋润啊！！！"
tag:
  thirst: "§b增加 §2<%:numf1> §b滋润度."
water:
  default: default-water
  biome: {}
