# 是否启用
enable: true

##############################################
#                  机器设定
##############################################
machine:
  tag:
    # 机器Lore格式
    lore-machine: "机器: <%:str>"
  # 最大多机器方块
  max-structure-block: 81
  # 机器数据更新间隔，单位毫秒
  update-period: 40

enable-minecraft-recipe: true

##############################################
#               配方合成工具设定
##############################################
# 若启用则能够实现在合成过程中
# * 不直接扣除参与合成的原材料物品、仅扣除其耐久值
# * 不扣除参与合成的原材料物品
recipe-tool:
  # 是否启用
  enable: true
  tag:
    # 工具耐久Lore格式
    lore-tool-durability: "当前耐久度: <%:int>"
    # 工具耐久NBT显示格式
    nreq-tool-durability: "当前耐久度: <%:int>"
    # 非消耗品合成原材料Lore格式
    lore-recipe-not-consumable: "在合成中不被消耗"
